apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stock-py
resources:
  - namespace.yaml
  - configmap.yaml
  - workloads.yaml
  - batch-jobs.yaml
  - observability.yaml
labels:
  - pairs:
      app.kubernetes.io/name: stock-py
      app.kubernetes.io/part-of: stock-py