server {
    listen 80;
    server_name _;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    location /v1/admin/ {
        proxy_pass http://admin-api:8001;
    }

    location /admin/docs {
        proxy_pass http://admin-api:8001/docs;
    }

    location /admin/redoc {
        proxy_pass http://admin-api:8001/redoc;
    }

    location /admin/metrics {
        proxy_pass http://admin-api:8001/metrics;
    }

    location /health {
        proxy_pass http://public-api:8000/health;
    }

    location /metrics {
        proxy_pass http://public-api:8000/metrics;
    }

    location / {
        proxy_pass http://public-api:8000;
    }
}