server {
    listen 80;
    server_name _;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $admin_api_upstream admin-api:8001;
    set $public_api_upstream public-api:8000;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;

    location /v1/admin/ {
        proxy_pass http://$admin_api_upstream;
    }

    location /admin/docs {
        proxy_pass http://$admin_api_upstream/docs;
    }

    location /admin/redoc {
        proxy_pass http://$admin_api_upstream/redoc;
    }

    location /admin/metrics {
        proxy_pass http://$admin_api_upstream/metrics;
    }

    location /health {
        proxy_pass http://$public_api_upstream/health;
    }

    location /metrics {
        proxy_pass http://$public_api_upstream/metrics;
    }

    location / {
        proxy_pass http://$public_api_upstream;
    }
}