const pythonBin = process.env.PYTHON_BIN || './.venv/bin/python';

const baseEnv = {
  ENVIRONMENT: 'production',
  DEBUG: 'false',
  LOG_LEVEL: 'INFO',
};

export default {
  apps: [
    {
      name: 'stock-py-public-api',
      script: pythonBin,
      args: ['-m', 'uvicorn', 'apps.public_api.main:app', '--host', '0.0.0.0', '--port', '8000'],
      interpreter: 'none',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '600M',
      kill_timeout: 10000,
      listen_timeout: 5000,
      wait_ready: false,
      env: {
        ...baseEnv,
        PUBLIC_API_PORT: '8000',
      },
      error_file: './logs/public-api-error.log',
      out_file: './logs/public-api-out.log',
    },
    {
      name: 'stock-py-admin-api',
      script: pythonBin,
      args: ['-m', 'uvicorn', 'apps.admin_api.main:app', '--host', '0.0.0.0', '--port', '8001'],
      interpreter: 'none',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '512M',
      kill_timeout: 10000,
      listen_timeout: 5000,
      wait_ready: false,
      env: {
        ...baseEnv,
        ADMIN_API_PORT: '8001',
      },
      error_file: './logs/admin-api-error.log',
      out_file: './logs/admin-api-out.log',
    },
    {
      name: 'stock-py-scheduler',
      script: pythonBin,
      args: ['-m', 'apps.scheduler.main'],
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '256M',
      env: {
        ...baseEnv,
        RUNTIME_COMPONENT_KIND: 'scheduler',
        RUNTIME_COMPONENT_NAME: 'scheduler',
      },
      error_file: './logs/scheduler-error.log',
      out_file: './logs/scheduler-out.log',
    },
    {
      name: 'stock-py-event-pipeline',
      script: pythonBin,
      args: ['-m', 'apps.workers.event_pipeline.worker'],
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '256M',
      env: {
        ...baseEnv,
        RUNTIME_COMPONENT_KIND: 'worker',
        RUNTIME_COMPONENT_NAME: 'event-pipeline',
      },
      error_file: './logs/event-pipeline-error.log',
      out_file: './logs/event-pipeline-out.log',
    },
    {
      name: 'stock-py-retention',
      script: pythonBin,
      args: ['-m', 'apps.workers.retention.worker'],
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '256M',
      env: {
        ...baseEnv,
        RUNTIME_COMPONENT_KIND: 'worker',
        RUNTIME_COMPONENT_NAME: 'retention',
      },
      error_file: './logs/retention-error.log',
      out_file: './logs/retention-out.log',
    },
    {
      name: 'stock-py-tradingagents-bridge',
      script: pythonBin,
      args: ['-m', 'apps.workers.tradingagents_bridge.worker'],
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '256M',
      env: {
        ...baseEnv,
        RUNTIME_COMPONENT_KIND: 'worker',
        RUNTIME_COMPONENT_NAME: 'tradingagents-bridge',
      },
      error_file: './logs/tradingagents-bridge-error.log',
      out_file: './logs/tradingagents-bridge-out.log',
    },
  ],
};