apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stock-py-staging
resources:
  - ../../base
patches:
  - path: release-shape.patch.yaml
labels:
  - pairs:
      app.kubernetes.io/environment: staging